// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4CakzcJErbOJOwMAdL88DkxrmDSmoboQ',
    appId: '1:495035301106:web:ddb8dbb961acc72440a46b',
    messagingSenderId: '495035301106',
    projectId: 'fala-doutor-challenge',
    authDomain: 'fala-doutor-challenge.firebaseapp.com',
    storageBucket: 'fala-doutor-challenge.firebasestorage.app',
    measurementId: 'G-CSPMCBKZRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiOEYwchQDJhRjTG5myIOAiOEV-o4COQ',
    appId: '1:495035301106:android:0451bcd8ea28c9e940a46b',
    messagingSenderId: '495035301106',
    projectId: 'fala-doutor-challenge',
    storageBucket: 'fala-doutor-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNy83LCJo79yKQBlnHUQSvJFJXDp6WoU',
    appId: '1:495035301106:ios:2e54396edb9b89b740a46b',
    messagingSenderId: '495035301106',
    projectId: 'fala-doutor-challenge',
    storageBucket: 'fala-doutor-challenge.firebasestorage.app',
    iosBundleId: 'com.example.falaDoutorChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNy83LCJo79yKQBlnHUQSvJFJXDp6WoU',
    appId: '1:495035301106:ios:2e54396edb9b89b740a46b',
    messagingSenderId: '495035301106',
    projectId: 'fala-doutor-challenge',
    storageBucket: 'fala-doutor-challenge.firebasestorage.app',
    iosBundleId: 'com.example.falaDoutorChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4CakzcJErbOJOwMAdL88DkxrmDSmoboQ',
    appId: '1:495035301106:web:83a60fe62085329540a46b',
    messagingSenderId: '495035301106',
    projectId: 'fala-doutor-challenge',
    authDomain: 'fala-doutor-challenge.firebaseapp.com',
    storageBucket: 'fala-doutor-challenge.firebasestorage.app',
    measurementId: 'G-2HVK2VSGF3',
  );
}
